### ISSUE TITLE
Improve command line argument handling

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/guacamole#106]
The Args4j (inherited from ADAM) library seems pretty clunky. We should figure out how to address some of these annoyances with it or switch to a better library if there is one (needs investigating):

 * The single dash (-) arguments feel ancient. Can it be made to work with GNU style arguments?
 * Args4j sorts all the arguments alphabetically, so we lose the logical grouping of arguments, and end up with e.g. obscure things at the top.
 * Args4j truncates the help message strings for the arguments, so we can't have detailed descriptions.
 * Need to be able to have a general usage statement / example at the top of the help output for a command instead of just the plain Args4j argument summary.

**Comment by ryan-williams** [comment]
Some of this has been done (move to GNU-style double-dashed args), some won't be (fix lots of Args4j rough edges), and some will be addressed by #553 (supporting JSON configs), so I'm going to close this.
