### ISSUE TITLE
Get structural variant caller from Cornell into master

### ISSUE THREAD

**Issue by hammer** [hammerlab/guacamole#289]
Code's at https://github.com/jdkizer9/guacamole/tree/development/structural-variant-caller

**Comment by hammer** [comment]
Related to #125, #131

**Comment by hammer** [comment]
@timodonnell and @ryan-williams, would you mind bringing @danvk up to speed on what was done by @jdkizer9? Dan's going to pick up this task as a good way to start learning about Spark and Guacamole.

**Comment by arahuja** [comment]
I don't think this is a goal anymore or has been superceded by Dan's work?

**Comment by timodonnell** [comment]
Yeah @danvk 's work superseded this. Closing
