### ISSUE TITLE
Remove requirement on MDTag for MappedRead

### ISSUE THREAD

**Issue by arahuja** [hammerlab/guacamole#297]
We may want to analysis mapped reads without the reference information, so we not care if they are MDTagged - should we remove this requirement? cc @ryan-williams @timodonnell

**Comment by timodonnell** [comment]
Sure, I feel like my argument to avoid having an `Option` here was kind of
crazy

**Comment by ryan-williams** [comment]
yea. options:

1. `MDTag` → `Option[MDTag]`
2. two different classes, `ReadWithMDTag` and `ReadWithoutMDTag`

@timodonnell I don't think it was crazy. those were dark times and we needed to tighten the belt

**Comment by arahuja** [comment]
@timodonnell you mentioned taking this one, do you have an idea on the approach you were thinking.  The two mentioned by @ryan-williams  seem the most reasonable.  I have a slight preference for the second as for pileup processing should only work with mdtagged reads for now, other than *always* checking an option

**Comment by timodonnell** [comment]
My vote is for option (1), as I think eventually we'll want to implement #333 and once we do that, it should be a runtime decision based on user options whether to load the reference from the mdtags or from another source, not a static decision we want to enforce with the type system.

Two short term goals:
 * It should be possible to analyze non-mdtagged reads if your analysis doesn't need reference info
 * If your analysis does require reference info (e.g. variant calling), if you run on non-mdtagged reads, you should get a reasonable error message, not something like "you have 0 reads in that bam file."

I think we should make mdTag an Option and in https://github.com/hammerlab/guacamole/blob/master/src/main/scala/org/hammerlab/guacamole/reads/Read.scala#L232 return a read without an mdtag, but also continue to throw an error if `requireMDTagsOnMappedReads=true` (so commands have an easy way of telling users they need to have mdtagged reads).

**Comment by danvk** [comment]
FWIW, I don't care at all about MDTags for split read analysis. I only discovered that this filter was happening when I noticed that ~99% of my alignments were getting dropped from a test BAM file.

**Comment by danvk** [comment]
@timodonnell @arahuja and @ryan-williams and I [discussed this][1] yesterday. To summarize:

- We'll have three read types: `Read`, `MappedRead` and `MDTaggedRead`.
- `MappedRead` will have `Option[MDTag]`
- `MDTaggedRead` will have a mandatory `MDTag` field, like `MappedRead` currently does.
- We may or may not have `MDTaggedRead` inherit from `MappedRead`.
- We'd like to stay open to the possibility of supporting BAM+FASTA in lieu of MDTagged BAM, but this will be a bigger change.

[1]: https://hammerlab.slack.com/archives/hammerlab/p1438280444001707
