### ISSUE TITLE
Standardize on @Opt or @Option

### ISSUE THREAD

**Issue by danvk** [hammerlab/guacamole#306]
I ran `git grep @Option` to find all the command line flags. It took me a minute to realize that some classes alias `Option` to `Opt`. Saving three characters doesn't seem particularly useful—we should just use one or the other.

**Comment by arahuja** [comment]
This is usually because a class collision between the Scala `Option` and the one from `Args4j`.  I think the best solution would be always alias the `Args4j` one  as `Args4jOption`
