### ISSUE TITLE
vaf histogram improvements

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/guacamole#315]
Some ideas:

 * output to csv with fields sample, start vaf, end vaf, count e.g. pt189_normal, 0.0, 0.1, 1000
 * accept an argument like --min-depth to control the minimum number of reads that must overlap a locus in order for it to be included

**Comment by arahuja** [comment]
The second one is actually why I left `PileupFilterArguments` on there, but didn't use it in the end.
