### ISSUE TITLE
incorrect comment / can't run single unit test

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/guacamole#321]
We say:
```
// You can use a line like the following to turn on only a particular unit test for debugging.
  // TestUtil.runOnly = "partitionLociByApproximateReadDepth chr20 synth1 subset"
```
here:
https://github.com/hammerlab/guacamole/blob/master/src/test/scala/org/hammerlab/guacamole/DistributedUtilSuite.scala#L35
and also: https://github.com/hammerlab/guacamole/blob/master/src/test/scala/org/hammerlab/guacamole/util/TestUtil.scala#L46

however, setting neither of these for me limits the tests to a single case.

We should either fix this or delete those lines.

**Comment by ryan-williams** [comment]
FWIW I use a cmd like `mvn -Dsuites="*Foo*" test` to run only suites matching `*Foo*` (glob syntax).

`mvn -Dsuites="*Foo* bar" test` will only run tests matching `bar` in `*Foo*` suites.

**Comment by timodonnell** [comment]
Ah that's good to know, thanks @ryan-williams
