### ISSUE TITLE
inferredInsertSize is double what it should be

### ISSUE THREAD

**Issue by danvk** [hammerlab/guacamole#331]
I looked at `62ca5d58-fe16-4015-9bd1-353b02085553` in synth4 in both IGV and Guacamole.

IGV reports:

     left alignment: location=chr20:8,000,211
                      start=8,007,974 (+)
                      insert size = 243
     right alignment: location=chr20:8,000,211
                      start=8,008,116 (-)
                      insert size = -243

For the same read, Guacamole has:

    matePropertiesOpt.get().inferredInsertSize = Some(-565)

cc @arahuja

**Comment by danvk** [comment]
Actually that's not double — I'm not sure what the relationship between these two values is.

**Comment by danvk** [comment]
Guacamole agrees with samtools, so I'll close this out. I'll try to figure out what "inferred insert size" means—it doesn't seem to match my intuition.

**Comment by arahuja** [comment]
Yea, perhaps this has changed but samtools does define it as the `243` you'd expect:
```
insert size (difference btw 5' end of read & 5' end of mate), if possible, else 0. Negative if mate maps to lower position than read.
``

But it does depend on what the aligner puts in that field

**Comment by arahuja** [comment]
If we wanted to the 243 value we can always compute that directly as well, instead of saving it.

**Comment by danvk** [comment]
Here's what's going on:

- Guacamole pulls the `inferredInsertSize` field straight from `htsjdk.samtools`.
- What `htsjdk.samtools` calls `inferredInsertSize`, the samtools paper calls "template length". It's the total span of the mate pairs on the reference, including aligned sections and the insert between mates.

For this read pair:

```
 left-most alignment =  8,007,725
right-most alignment = 8,008,288
```

Template length should be the difference, which comes out to 8211-7725=563.

The insert size, on the other hand, is 563-202, which is 361.
