### ISSUE TITLE
Code is licensed to BDG

### ISSUE THREAD

**Issue by danvk** [hammerlab/guacamole#332]
Most of our scala files are ["Licensed to Big Data Genomics (BDG)"][1]. Is this intentional?

[1]: https://github.com/hammerlab/guacamole/blob/b8ac2e564ad1fe0000641314d27a7643d66473b4/src/main/scala/org/hammerlab/guacamole/Guacamole.scala#L2

**Comment by hammer** [comment]
Yeah we were planning on trying to pool our code with theirs back in the day. I'm indifferent at this point on whether we want to keep it that way.

**Comment by arahuja** [comment]
@ryan-williams @timodonnell Any thoughts on copyright/licensing?  I think we have new source without any copyright headers at all.

**Comment by danvk** [comment]
So long as you have a `LICENSE` file in your repo, there's no need to have a copyright header in every file. The copyright belongs to whoever it belongs to either way. As an example, Google used to require that we put copyright notices in all source code developed internally but dropped the requirement a few years back.

**Comment by timodonnell** [comment]
less boilerplate sounds good to me
