### ISSUE TITLE
support loading the reference from a fasta instead of relying on mdtags

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/guacamole#333]
Guacamole currently expects the reference genome to be encoding in the reads using the mdtag mechanism. Since mdtags are frequently NOT written by aligners, it would be useful to also support loading in the reference from a user-specified fasta file, as most variant callers do.

It would be great to somehow do this at the pileup level, so individual guacamole commands can be oblivious to whether the reference is coming from a fasta or from the mdtags.

**Comment by arahuja** [comment]
This was resolved in a large part by #355 but could use improvements.  If there are things lacking from that that you were thinking of @timodonnell can you open another issue?
