### ISSUE TITLE
implement an adaptive read partitioning strategy

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/guacamole#348]
In situations with very high read skew, which often happens with RNA, it would be good if `DistributedUtil.partitionLociByApproximateDepth` would adaptively refine the granularity if the read-depth approximation. E.g. if a single micro partitions has > 10% the total number of reads, then calculate another depth histogram just within that micro partition.

**Comment by ryan-williams** [comment]
I think this is superseded by #425 and the "capped regions" partitioner.
