### ISSUE TITLE
Cap the number of reads that are materialized in a Pileup

### ISSUE THREAD

**Issue by ryan-williams** [hammerlab/guacamole#425]
Per discussion we had last week, this is the quickest way to work around the most frequent cause of memory pressure that we run in to.

**Comment by ryan-williams** [comment]
There are a few ways to approach this:

### Drop reads in `SlidingWindow`

[`SlidingWindow.setCurrentLocus`](https://github.com/hammerlab/guacamole/blob/9cca752f06fd4c4c5df52de05d09c0bca54a8f45/src/main/scala/org/hammerlab/guacamole/windowing/SlidingWindow.scala#L95-L110) could be made to dequeue reads as it adds new ones when there are currently ≥ `max` reads in the window.

This is the simplest salve but has a few downsides:

- We would likely drop from the start of the window and only keep the right-most `max` reads.
  - In extreme high depth regions (e.g. 1MM depth with a cap of 10k reads per window), this would likely result in window that have only 10k reads at `locus + halfWindowSize - 1`, the far right edge of the sliding window, with none overlapping the locus of interest.
  - This would be at best useless / result in no-op processing at such loci, and at worst could produce actively incorrect downstream results.
  - Attempting to mitigate this by dropping from any reads other than the left-most ones would result in subsequent loci missing reads that they should have legitimately had access to.
- It spends upstream resources processing/partitioning extreme-depth regions only to mangle them later.

A likely better alternative is:

### Drop reads during partitioning

It probably makes more sense to nip the skew in the bud further upstream, when reads and loci-intervals are being assigned to partitions.

Further questions about how to do so:

#### Per-sample vs. across all samples
Should we flag/truncate loci where any sample exceeds `max` reads, or just where the total number of reads across samples exceeds `max`?

#### How/whether to propagate truncated regions downstream

When we find extreme-depth regions, should we:

1. drop them from the set of loci to be processed?
2. truncate to `max` reads and send them downstream as if nothing happened?
3. truncate to `max` reads and add metadata to `Pileup` or `SlidingWindow` to indicate that `N` reads were dropped, possibly including summary info about them, so e.g. callers can decide what to do at such loci.

I think 1. seems like the most sensible first pass; a cmdline param would indicate the (total or per-sample?) depth past which to consider loci invalid / suspicious / unworthy of calling variants at; other callers do basically this already, afaik.

**Comment by timodonnell** [comment]
Thanks for digging into this @ryan-williams , these seem like good options

I'd be curious if we can figure out where exactly skew is causing us to OOM, i.e. is it while generating a particular Pileup or somewhere before that (like when the reads are getting scattered to the nodes)?

I like your idea to deal with this during read partitioning. One thing to note is that our micro partitions for read partitioning are still often quite large at typical settings (e.g. 3e9 bases / 200,000 micro partitions = 15kb / partition). For a final solution we probably want to handle these issues at a finer level of granularity. Also I think *some* of the skew-related crashes might be addressed by doing better read partitioning, which when possible would be preferable (https://github.com/hammerlab/guacamole/issues/348)

If option 1 helps us get a handle on what's going on as a quick first pass that makes sense to me too. But to handle RNA (where huge skew is expected and not a sign that anything's wrong with a region) in the long run I think we'll need option 3 (```truncate to max reads and add metadata to Pileup or SlidingWindow to indicate that N reads were dropped, possibly including summary info about them, so e.g. callers can decide what to do at such loci.```) I think handling this per-sample is a bit better than doing it over all samples but it would also depend on how complex it is to implement that

**Comment by ryan-williams** [comment]
Option 1. was merged in with the `CappedRegionsPartitioner` in #501, marking this done.
