### ISSUE TITLE
Move `Common` functionality to more specific locations

### ISSUE THREAD

**Issue by ryan-williams** [hammerlab/guacamole#465]
Outstanding PRs already move everything out of `Common` piecemeal, and delete it:

- #461: `createSparkContext`
- #464: `validateArguments`, `parseEnvVariables`
- #459: loci-parsing functions

This issue just notes the above and the high-level goal of putting `Common` things in modules and removing it, to better organize the codebase.

**Comment by arahuja** [comment]
@ryan-williams Are there more tasks to this?

**Comment by ryan-williams** [comment]
I think that #432 finishes this, which seems to be almost gtg after @timodonnell's last round of comments which I'll hopefully turn around today!
