### ISSUE TITLE
Move files out of root packages

### ISSUE THREAD

**Issue by ryan-williams** [hammerlab/guacamole#466]
Similar to #465, this issue is just to note that the following PRs/commits move everything from the root `org.hammerlab.guacamole` package (both `src/` and `test/`) and in to more specific sub-packages with like functionality:

- #463: `HasReferenceRegion` → `reference.Region`
- #462: `Bases`, `CigarUtils` → `util` pkg
- #461: `Command`, `SparkCommand` → `commands` pkg
- #464 (specifically https://github.com/hammerlab/guacamole/pull/464/commits/11b66bdbc38f89a987d4fe1706e6762c2d5aa20d): `test/…/{NA12878TestUtils,CancerWGSTestUtils}` → `test/…/data/{NA12878,CancerWGS}`

The end result of this and #465, with all my outstanding PRs rebased on one another, can be seen at https://github.com/ryan-williams/guacamole/tree/tot; one commit, https://github.com/ryan-williams/guacamole/commit/7daf23ec092ad11d2d9ca2c3aee9f4d5d106c72a, is not in any PR yet, but I'll add it to one or make it its own soon.

File hierarchy, as viewed in IntelliJ, before these changes:

![](http://cl.ly/2j3L3k032q3H/Screen%20Shot%202016-04-30%20at%205.42.47%20PM.png)

and after:

![](http://f.cl.ly/items/2K2p2C370m0T3s2v0v2r/Screen%20Shot%202016-04-30%20at%205.42.11%20PM.png)

**Comment by arahuja** [comment]
@ryan-williams seems complete? More to do?

**Comment by ryan-williams** [comment]
Yea I think it's done, thanks!
