### ISSUE TITLE
SomaticJointCallerIntegrationTests are broken

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/guacamole#483]
The SomaticJointCallerIntegrationTests (which have been refactored to be a standalone entry point instead of a test since since the last time I used them), give these instructions for how to run them:

```
 * To run:
 *
 *   mvn package
 *   mvn test-compile
 *   java \
 *     -cp target/guacamole-with-dependencies-0.0.1-SNAPSHOT.jar:target/scala-2.10.5/test-classes \
 *     org.hammerlab.guacamole.main.SomaticJointCallerIntegrationTests
```

However, when I do that, I get this usage error followed by the joint caller help message:

```
[tim@Tims-MacBook ~/sinai/git/guacamole]$  java \
>       -cp target/guacamole-with-dependencies-0.0.1-SNAPSHOT.jar:target/scala-2.10.5/test-classes \
>       org.hammerlab.guacamole.main.SomaticJointCallerIntegrationTests
Option "--reference-fasta" is required
```

Also, it's unclear to me how to run these from IntelliJ.

I'm thinking we should probably roll back the change that made these non-tests. Even though they don't assert anything, by the fact that they run successfully they effectively test a number of things. Having them as tests also makes sure we don't end up in the current situation where they bit rot.

**Comment by ryan-williams** [comment]
Sorry these were rotting @timodonnell, I just sent out #484 which fixes the argument-initialization issue you hit; you can run them now like so ([cf. file comment](https://github.com/hammerlab/guacamole/pull/484/files#diff-fcfa328d38b39e6f26b72cde5483badcR20)):

```
mvn package -DskipTests
mvn test-compile
java \
  -Xmx4g \
  -cp target/guacamole-with-dependencies-0.0.1-SNAPSHOT.jar:target/scala-2.10.5/test-classes \
  org.hammerlab.guacamole.main.SomaticJointCallerIntegrationTests
```

I disagree that our test infrastructure should be used to run this. Despite its name including "Test", it asserts nothing, prints a wall of stdout that afaik no one but you knows what to look for within, takes ~10x as long as all of our other tests combined, and makes my laptop unusable for anything else during its duration. 

If you want to serialize some of what you think is important about its output to code, we can talk about having e.g. Travis run it as part of testing PRs, but without some significant changes I don't think running it as part of our unittesting infrastructure (that a person can currently run locally without too much headache) makes sense.

Here is a screenshot of my working configuration for running it in IntelliJ:

![](https://cl.ly/0J1y0Q231o3z/Screen%20Shot%202016-07-10%20at%2012.13.18%20PM.png)

NB: this kind of configuration would work for any Java application. IntelliJ's ScalaTest integration is not a good thing to overload to get around specifying a classpath and main class for something that is not a unit-test.

**Comment by timodonnell** [comment]
Cool, thanks for the fix @ryan-williams and instructions for running in intellij.  Definitely see your points for not to have these as unit tests, I'm fine having them as separate programs
