### ISSUE TITLE
run joint caller integration tests in travis

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/guacamole#507]
It would be useful to continuously verify that we can run the joint caller and get reasonable output. That test is currently quite slow though so it has been removed from the unit tests. It would be great to have it run as part of travis though. Some profiling and performance optimization of it might be useful too. 

See discussion at https://github.com/hammerlab/guacamole/issues/483#issuecomment-231597188

**Comment by ryan-williams** [comment]
Doesn't [`SomaticJointCallerSuite`](https://github.com/hammerlab/guacamole/blob/b379defd0825afd047aec3bda43189eba7d43bde/src/test/scala/org/hammerlab/guacamole/commands/jointcaller/SomaticJointCallerSuite.scala) basically do this?

**Comment by timodonnell** [comment]
It tests a bunch of things but still the joint caller integration tests seem to easily end up in a non-runnable state due to other refactorings in the code. Examples are #483 and #506 if @arahuja hadn't noticed the loss of VCF support in loci loading

**Comment by ryan-williams** [comment]
It is definitely desirable to end-to-end test our callers, e.g. to catch cmdline-arg-parsing regressions, and it's very straightforward to write tiny tests that do so.

I've written a very simple end-to-end SJC unittest in #508 demonstrating this; it verifies that SJC can parse its command-line args correctly, load loci-specifications from .vcf files, etc.

It runs on 3 bams that are 1000bp either side of one locus of interest, about 1/1000th the size of the ones SJCIntegrationTest is running on and not verifying anything about, uses input and output VCFs that include only that locus, and leverages all of SJC from cmdline-arg-parsing through output-writing.

This is a much better way to test the things you're interested in. Let me know if that is not what you have in mind here!
