### ISSUE TITLE
time how long it takes to do the actual variant calling in threshold caller

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/guacamole#81]
We need to know how long we're spending doing actual variant calling ( threshold.callVariantsAtLocus) vs. Spark data shuffling, etc. One way to do this would be to log a message in callVariantsAtLocus every X loci, and aggregate those logs. Another way would be to rig up a profiler.

**Comment by arahuja** [comment]
@timodonnell close? I think you have some benchmarks alreadt?
